CREATE TABLE SENSORES_AGRICOLAS (
    ID_SENSOR NUMBER PRIMARY KEY,
    DATA_COLETA DATE,
    CULTURA VARCHAR2(50),
    UMIDADE_SOLO NUMBER(10,2),
    PH_SOLO NUMBER(10,2),
    TEMPERATURA_C NUMBER(10,2),
    IRRIGACAO_MM NUMBER(10,2),
    FERTILIZANTE_KG NUMBER(10,2),
    PRODUTIVIDADE_KG_HA NUMBER(10,2)
);
